### ISSUE TITLE
Integration with Ansible?

### ISSUE THREAD

**Issue by ildjarnisdead** [mozilla/http-observatory#539]
Hello,

Has anyone got this working with Ansible? I tried installing this in an Ansible EE, but the `httpobs.scanner` module isn't found

The Ansible-builder execution-environment.yml I used:

```yaml
---
version: 3
images:
  base_image:
    name: quay.io/fedora/python-311:311
dependencies:
  ansible_core:
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  python: |
    poetry
  system: |
    python3.11-devel [platform:rpm compile]
    git [platform:rpm]
    postgresql-devel [platform:rpm]
    gcc [platform:rpm]
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - RUN git clone https://github.com/mozilla/http-observatory.git && cd http-observatory && poetry install --no-interaction
```
